POST http://localhost:8000/auth/register HTTP/1.1
content-type: application/json

{
    "username": "guss",
    "password": "pass1234"
}

###

POST http://localhost:8000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "guss",
    "password": "pass1234"
}

###

GET http://localhost:8000/auth/profile HTTP/1.1
# Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZjNlZWNlNC0yZjViLTQ3N2YtYmU3ZC1lZmZmMTFlYWZiZDYiLCJ1c2VybmFtZSI6Imd1c3MiLCJpYXQiOjE3NzIwODcwMTQsImV4cCI6MTc3MjE3MzQxNH0.ivw_IO9NCeUdiNVTVMe2HuK2_UxnLXuYXgZBMYW1ABo; Max-Age=86400; Path=/; Expires=Fri, 27 Feb 2026 06:23:34 GMT; HttpOnly; SameSite=Lax

###

GET http://localhost:8000/auth/logout HTTP/1.1